import React from "react";
import type { Metadata } from "next";
import InnerNav from "@/components/ui/inner-nav";
import Filter from "@/components/ui/filter";
import PopoverForm from "@/components/ui/popover-form";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const innerNavItems = [
  {
    title: "Task 1",
    href: "/admin/tasks/task-1",
  },
  {
    title: "Task 2",
    href: "/admin/tasks/task-2",
  },
];

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="grid min-h-screen w-full md:grid-cols-[220px_1fr] lg:grid-cols-[280px_1fr] ">
      <div className="h-screen w-full">
        <div className="w-full h-[58px] flex items-center">
          <h1 className="text-2xl font-bold">Tasks</h1>
        </div>
        <div className="flex gap-2">
          <Filter items={innerNavItems} />
          <PopoverForm />
        </div>
        <InnerNav className="" navItems={innerNavItems} />
      </div>
      <div className="flex flex-col">{children}</div>
    </div>
  );
}
